# I. Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
import time 
import re

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn import metrics

from scipy import stats

import requests
import pickle
import joblib

import re
from wordcloud import WordCloud
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

# II. Function that will be called by Preprocess methods

In [3]:
def get_average_area(x):
    regx_numbers = re.compile(r"[-+]?(\d*\.\d+|\d+)")
    x = regx_numbers.findall(x)
    if len(x) == 1:
        return (np.float(x[0]))
    elif len(x) == 2:
        return (np.float(x[0]) + np.float(x[1]))/2
    else:
        return -99

In [4]:
def get_outlier_range(df,cname):
    sorted(cname)
    llimit = df[cname].quantile(0.25)
    hlimit = df[cname].quantile(0.95)
    return llimit, hlimit

In [5]:
# Setting up stopwords for Text Processing
stopwords_list = set(stopwords.words('english'))

#Custom Stoplist
custome_stopwords= ["i","project","living","home",'apartment',"pune","me","my","myself","we","our","ours","ourselves","you",
                  "you're","you've","you'll","you'd","your","yours","yourself","yourselves","he","him","his","himself","she",
                  "she's","her","hers","herself","it","it's","its","itself","they","them","their","theirs","themselves",
                  "what","which","who","whom","this","that","that'll","these","those","am","is","are","was","were","be","been",
                  "being","have","has","had","having","do","does","did","doing","a","an","the","and","but","if","or","because",
                  "as","until","while","of","at","by","for","with","about","against","between","into","through","during",
                  "before","after","above","below","to","from","up","down","in","out","on","off","over","under","again",
                  "further","then","once","here","there","when","where","why","all","any","both","each","few","more","most",
                  "other","some","such","no","nor","not","only","own","same","so","than","too","very","s","t","can","will",
                  "just","don","don't","should","should've","now","d","ll","m","o","re","ve","y","ain",
                  "aren","couldn","didn","doesn","hadn","hasn","haven","isn","ma","mightn","mustn","needn","shan","shan't",
                  "shouldn","wasn","weren","won","rt","rt","qt","for","the","with","in","of","and","its","it","this","i",
                  "have","has","would","could","you","a","an","be","am","can","edushopper","will","to","on","is","by","ive",
                  "im","your","we","are","at","as","any","ebay","thank","hello","know","need","want","look","hi","sorry",
                  "http", "https","body","dear","hello","hi","thanks","sir","tomorrow","sent","send","see","there","welcome",
                  "what","well","us"]

stopwords_list.update(custome_stopwords)

In [6]:
# Function to preprocess the text
def text_preprocess(text):
    """
        text: a string    
        return: modified initial string
    """
    text = text.replace("\d+"," ") #removing digits
    text = re.sub(r"(?:\@|https?\://)\S+",'',text) #removing mentions and urls
    text = text.lower()
    text = re.sub('[0-9]+','',text) #removing numeric characters
    text = re.sub('[/(){}\[\]\|@,;!]',' ',text) # replace REPLACE_BY_SPACE_RE symbols by space in text
    text = re.sub('[^0-9a-z #+_]',' ',text) # replace symbols which are in BAD_SYMBOLS_RE from text
    
    text = ' '.join([word for word in text.split() if word not in stopwords_list])
    text = text.strip()
    return text

In [7]:
def get_pos_counter(text,part_of_speech):
    """
    Returns the count for the given parts of speech tag
    
    NN - Noun
    VB - Verb
    JJ - Adjective
    RB - Adverb
    """
    word_list = nltk.word_tokenize(text.lower())
    clean_word_list = [word for word in word_list if word not in stopwords_list]
    text = nltk.Text(clean_word_list)
    tag_pos = nltk.pos_tag(text)
    counts = Counter(tag for word,tag in tag_pos)
    return counts[part_of_speech]

In [8]:
def get_interval(train_actual_values, train_predicted_values, pi=.60):
    '''
    Get a prediction interval for the regression model.
    
    INPUTS: 
        - actual_values (y_train)
        - predicted_values (prediction from x_train)
        - Prediction interval threshold (default = .95) 
    OUTPUT: 
        - Interval estimate
    '''
    
    #get standard deviation of prediction on the train dataset
    sum_of_square_error = np.sum((train_actual_values - train_predicted_values)**2)
    stdev = np.sqrt(sum_of_square_error / (len(train_actual_values) - 1))
    
    #get interval from standard deviation
    one_minus_pi = 1 - pi
    ppf_lookup = 1 - (one_minus_pi / 2) # If we need to calculate a 'Two-tail test' (i.e. We're concerned with values both greater and less than our mean) then we need to split the significance (i.e. our alpha value) because we're still using a calculation method for one-tail. The split in half symbolizes the significance level being appropriated to both tails. A 95% significance level has a 5% alpha; splitting the 5% alpha across both tails returns 2.5%. Taking 2.5% from 100% returns 97.5% as an input for the significance level.
    z_score = stats.norm.ppf(ppf_lookup) # This will return a value (that functions as a 'standard-deviation multiplier') marking where 95% (pi%) of data points would be contained if our data is a normal distribution.
    interval_value = z_score * stdev
    
    return interval_value

In [9]:
def get_prediction_interval(y_predicted_value, interval_value):
    
    #generate prediction interval lower and upper bound cs_24
    lower, upper = y_predicted_value - interval_value, y_predicted_value + interval_value
    return lower, upper

# III. Preprocess methods

In [10]:
def preprocess_data(df):
    df_final = pd.DataFrame()
    df_final['City'] = df['Location'].apply(lambda x : x.split(',')[0].strip())
    df_final['State'] = df['Location'].apply(lambda x : x.split(',')[1].strip())
    df_final['Country'] = df['Location'].apply(lambda x : x.split(',')[2].strip())
    
    regx_numbers = re.compile(r"[-+]?(\d*\.\d+|\d+)")
    df_final['PropertyType'] = df['Propert Type'].apply(lambda x : regx_numbers.findall(x)[0] 
                                                     if len(regx_numbers.findall(x)) > 0 else 0)
    
    df_final['SubArea'] = df['Sub-Area'].apply(lambda x: x.capitalize().strip())
    df_final['CompanyName'] = df['Company Name'].apply(lambda x : x.capitalize())
    df_final['TownshipSocietyName'] = df['TownShip Name/ Society Name'].apply(lambda x: x.capitalize())
    df_final['Description'] = df['Description'].apply(lambda x : x.capitalize())
    
    regx_numbers = re.compile(r"[-+]?(\d*\.\d+|\d+)")
    df_final['PropertyAreainSqFt'] = df['Property Area in Sq. Ft.'].apply(lambda x : get_average_area(str(x)))
    
    # df_final['ClubHouse'] = df['ClubHouse'].apply(lambda x: x.lower().strip())
    # df_final['School/UniversityInTownship'] = df['School / University in Township '].apply(lambda x: x.lower().strip())
    # df_final['HospitalInTownShip'] = df['Hospital in TownShip'].apply(lambda x: x.lower().strip())
    # df_final['MallInTownShip'] = df['Mall in TownShip'].apply(lambda x: x.lower().strip())
    # df_final['ParkJoggingTrack'] = df['Park / Jogging track'].apply(lambda x: x.lower().strip())
    # df_final['SwimmingPool'] = df['Swimming Pool'].apply(lambda x: x.lower().strip())
    # df_final['Gym'] = df['Gym'].apply(lambda x: x.lower().strip())
        
    df_final['ClubHouse'] = df['ClubHouse'].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    df_final['School/UniversityInTownship'] = df['School / University in Township '].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    df_final['HospitalInTownShip'] = df['Hospital in TownShip'].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    df_final['MallInTownShip'] = df['Mall in TownShip'].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    df_final['ParkJoggingTrack'] = df['Park / Jogging track'].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    df_final['SwimmingPool'] = df['Swimming Pool'].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    df_final['Gym'] = df['Gym'].apply(lambda x: x.lower().strip()).map({'yes': 1, 'no': 0})
    
    df_final = df_final.dropna()
    
    return df_final

In [11]:
def create_features(df):
    # Treating outliers in the numeric columns
    clist = ['PropertyAreainSqFt']
    
    for col in clist:
        lval, hval = get_outlier_range(df,col)
        df[col] = np.where(df[col] >hval, hval, df[col])
        df[col] = np.where(df[col] <lval, lval, df[col])
    
    
    filename = 'model/price_by_sub_area.pkl'
    with open(filename,'rb') as f:
        Price_by_Sub_Area = pickle.load(f)
        
    df['PriceBySubArea']= df['SubArea'].map(Price_by_Sub_Area)
    
    
    amenities_cloumns = ['ClubHouse',
                         'School/UniversityInTownship',
                         'HospitalInTownShip',
                         'MallInTownShip',
                         'ParkJoggingTrack',
                         'SwimmingPool',
                         'Gym']
    
    temp_df = df[amenities_cloumns]
    temp_df['AmenitiesScore'] = temp_df.sum(axis=1)
    df['AmenitiesScore'] = temp_df['AmenitiesScore']
    
    filename = 'model/price_by_amenities_score.pkl'
    with open(filename,'rb') as f:
        price_by_amenities_score = pickle.load(f)
        
    df['PriceByAmenitiesScore'] = df['AmenitiesScore'].map(price_by_amenities_score)
    
    '''
        NLP Text Processing to extract new features
    '''
    
    df['Description'] = df["Description"].astype(str).apply(text_preprocess)
    df['Noun_Counts'] = df['Description'].apply(lambda x: get_pos_counter(x,'NN'))
    df['Verb_Counts'] = df['Description'].apply(lambda x: (get_pos_counter(x,'VB')+get_pos_counter(x,'RB')))
    df['Adjective_Counts'] = df['Description'].apply(lambda x: get_pos_counter(x,'JJ'))
    
    fileName = 'model/count_vectorizer.pkl'
    with open(fileName,'rb') as f:
        count_vectorizer = pickle.load(f)
        
    X = count_vectorizer.transform(df['Description'])
    ngram_df = pd.DataFrame(X.toarray(),columns=count_vectorizer.get_feature_names_out())
    df_final = pd.concat([df.reset_index(drop=True),ngram_df.reset_index(drop=True)],axis=1)

    # selecting the final model ready features
    fileName = 'model/raw_features_mapping.pkl'
    with open(fileName,'rb') as f:
        feature_mapping = pickle.load(f)   
        
    fileName = 'model/feature_mapping.pkl'
    with open(fileName,'rb') as f:
        final_feature_list = pickle.load(f)
        
    # Removing price column as it is not available in test data
    final_feature_list.remove('Price_In_Lakhs')

    df_final = df_final.rename(columns=feature_mapping)
    df_final = df_final[final_feature_list]
    
    return df_final

# Test Inference:

In [12]:
# Loading the data
data= pd.read_excel('data/Pune Real Estate Data.xlsx')
data = data.drop(['Price in Millions','Price in lakhs'],axis=1)
print(data.shape)
data.head()

(200, 16)

,Sr. No.,Location,Sub-Area,Propert Type,Property Area in Sq. Ft.,Company Name,TownShip Name/ Society Name,Total TownShip Area in Acres,ClubHouse,School / University in Township,Hospital in TownShip,Mall in TownShip,Park / Jogging track,Swimming Pool,Gym,Description
0,1,"Pune, Maharashtra, India",Bavdhan,1 BHK,492,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Shapoorji Paloonji comunity located in the sub...
1,2,"Pune, Maharashtra, India",Bavdhan,2 BHK,774,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha Township located near the lonavala hill...
2,3,"Pune, Maharashtra, India",Bavdhan,3 BHK,889,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha Society is suitable for all aged group ...
3,4,"Pune, Maharashtra, India",Bavdhan,3 BHK Grand,1018,Shapoorji Paloonji,Vanaha,1000.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Vanaha township are offering 3BHK grand prpoer...
4,5,"Pune, Maharashtra, India",Mahalunge,2BHK,743,Godrej Properties,Godrej Hills retreat,100.0,Yes,Yes,Yes,Yes,Yes,Yes,Yes,The area is a hub of prestigious schools like ...

In [13]:
df_preprocess = preprocess_data(data)
df_preprocess.head()

,City,State,Country,PropertyType,SubArea,CompanyName,TownshipSocietyName,Description,PropertyAreainSqFt,ClubHouse,School/UniversityInTownship,HospitalInTownShip,MallInTownShip,ParkJoggingTrack,SwimmingPool,Gym
0,Pune,Maharashtra,India,1,Bavdhan,Shapoorji paloonji,Vanaha,Shapoorji paloonji comunity located in the sub...,492.0,1,1,1,1,1,1,1
1,Pune,Maharashtra,India,2,Bavdhan,Shapoorji paloonji,Vanaha,Vanaha township located near the lonavala hill...,774.0,1,1,1,1,1,1,1
2,Pune,Maharashtra,India,3,Bavdhan,Shapoorji paloonji,Vanaha,Vanaha society is suitable for all aged group ...,889.0,1,1,1,1,1,1,1
3,Pune,Maharashtra,India,3,Bavdhan,Shapoorji paloonji,Vanaha,Vanaha township are offering 3bhk grand prpoer...,1018.0,1,1,1,1,1,1,1
4,Pune,Maharashtra,India,2,Mahalunge,Godrej properties,Godrej hills retreat,The area is a hub of prestigious schools like ...,743.0,1,1,1,1,1,1,1

In [14]:
df_preprocess.isnull().sum()

City                           0
State                          0
Country                        0
PropertyType                   0
SubArea                        0
CompanyName                    0
TownshipSocietyName            0
Description                    0
PropertyAreainSqFt             0
ClubHouse                      0
School/UniversityInTownship    0
HospitalInTownShip             0
MallInTownShip                 0
ParkJoggingTrack               0
SwimmingPool                   0
Gym                            0
dtype: int64

In [15]:
df_features = create_features(df_preprocess)
df_features.head()

,Property_Type,Club_House,School_University_In_Township,Hospital_In_Township,Mall_In_Township,Park_Jogging_Track,Swimming_Pool,Gym,Property_Area_in_SqFt,Price_By_SubArea,Amenities_Score,Price_By_Amenities_Score,Noun_Counts,Verb_Counts,Adjective_Counts,boasts_elegant,elegant_towers,every_day,great_community,mantra_gold,offering_bedroom,quality_specification,stories_offering,towers_stories,world_class
0,1,1,1,1,1,1,1,1,670.0,58.044000,7,72.666667,9,1,3,0,0,0,0,0,0,0,0,0,0
1,2,1,1,1,1,1,1,1,774.0,58.044000,7,72.666667,9,1,3,0,0,0,0,0,0,0,0,0,0
2,3,1,1,1,1,1,1,1,889.0,58.044000,7,72.666667,9,1,3,0,0,0,0,0,0,0,0,0,0
3,3,1,1,1,1,1,1,1,1018.0,58.044000,7,72.666667,8,1,3,0,0,0,0,0,0,0,0,0,0
4,2,1,1,1,1,1,1,1,743.0,73.555556,7,72.666667,12,1,6,0,0,0,0,0,0,0,0,0,0

In [16]:
df_features.loc[63:64]

,Property_Type,Club_House,School_University_In_Township,Hospital_In_Township,Mall_In_Township,Park_Jogging_Track,Swimming_Pool,Gym,Property_Area_in_SqFt,Price_By_SubArea,Amenities_Score,Price_By_Amenities_Score,Noun_Counts,Verb_Counts,Adjective_Counts,boasts_elegant,elegant_towers,every_day,great_community,mantra_gold,offering_bedroom,quality_specification,stories_offering,towers_stories,world_class
63,2.5,1,0,0,0,1,1,0,847.0,69.665,3,68.514348,11,0,8,0,0,0,0,0,0,0,0,0,0
64,2.5,1,0,0,0,1,1,0,936.0,69.665,3,68.514348,10,2,4,0,0,0,0,0,0,0,0,0,0

In [17]:
payload = df_features.iloc[15].to_dict()
#Even if an integer of the type int64 is present in another object like a dictionary, 
#the TypeError exception will occur with the message “TypeError: Object of type int64 is not JSON serializable”
import json
# define a class to avoid that
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)
    
payload = json.dumps(payload,cls=NpEncoder)

In [18]:
payload

'{"Property_Type": "1", "Club_House": 1, "School_University_In_Township": 0, "Hospital_In_Township": 0, "Mall_In_Township": 0, "Park_Jogging_Track": 1, "Swimming_Pool": 1, "Gym": 1, "Property_Area_in_SqFt": 670.0, "Price_By_SubArea": 73.55555555555556, "Amenities_Score": 4, "Price_By_Amenities_Score": 97.87350515463918, "Noun_Counts": 9, "Verb_Counts": 1, "Adjective_Counts": 3, "boasts_elegant": 0, "elegant_towers": 0, "every_day": 0, "great_community": 0, "mantra_gold": 0, "offering_bedroom": 0, "quality_specification": 0, "stories_offering": 0, "towers_stories": 0, "world_class": 0}'

In [20]:
output = []
for i in range(len(df_features)):
    payload = df_features.iloc[i].to_dict()
    payload = json.dumps(payload,cls=NpEncoder)
    
    out =  requests.post(url='https://propoert-price-prediction-prod-fbbed88de872.herokuapp.com/PredictPrice',
                    data=payload)
    result = np.float(re.sub('[^A-Za-z0-9.]+', ' ', out.text))  
    output.append(result)

In [21]:
import pickle
fileName = 'model/estimating_interval.pkl'
with open(fileName,'rb') as f:
    interval = pickle.load(f)

interval

15.038882262184757

In [22]:
# getting prediction intervals for the test data
lower_vet = []
upper_vet = []

for out in output:
    lower, upper =  get_prediction_interval(out, interval)
    lower_vet.append(lower)
    upper_vet.append(upper)

In [23]:
pd.DataFrame(zip(lower_vet,upper_vet,output),columns=['lower','upper','mean'])

          lower       upper        mean
0     26.009678   56.087443   41.048561
1     44.842812   74.920577   59.881695
2     64.325084   94.402849   79.363967
3     72.216431  102.294196   87.255314
4     55.401575   85.479340   70.440457
5     73.135544  103.213309   88.174427
6     68.742828   98.820593   83.781711
7     97.962169  128.039934  113.001052
8     64.038511   94.116275   79.077393
9     94.286532  124.364297  109.325415
10   137.076108  167.153873  152.114991
11   159.134283  189.212048  174.173165
12   161.584864  191.662629  176.623747
13    72.902815  102.980579   87.941697
14   106.769549  136.847313  121.808431
15    34.470088   64.547853   49.508971
16    47.738265   77.816030   62.777148
17    69.378570   99.456334   84.417452
18    43.592439   73.670203   58.631321
19    60.033126   90.110891   75.072009
20    62.820640   92.898405   77.859522
21    90.925064  121.002829  105.963946
22    24.838198   54.915963   39.877081
23    49.012234   79.089998   64.051116
24    39.578986   69.656750   54.617868
25    43.189805   73.267569   58.228687
26    53.118762   83.196526   68.157644
27    66.698106   96.775870   81.736988
28    62.961802   93.039567   78.000685
29    64.367049   94.444813   79.405931
30    70.430270  100.508034   85.469152
31    71.120883  101.198647   86.159765
32    86.890554  116.968318  101.929436
33    82.846839  112.924603   97.885721
34    93.253397  123.331162  108.292279
35    53.007018   83.084783   68.045900
36    93.820227  123.897992  108.859109
37    71.834491  101.912255   86.873373
38   105.438794  135.516559  120.477676
39    25.497770   55.575535   40.536652
40    56.009229   86.086993   71.048111
41   113.836587  143.914351  128.875469
42    12.518357   42.596122   27.557240
43    24.164279   54.242043   39.203161
44    35.036656   65.114421   50.075538
45    73.998677  104.076442   89.037560
46    75.148951  105.226715   90.187833
47   104.202250  134.280015  119.241132
48    97.840392  127.918156  112.879274
49   114.091536  144.169300  129.130418
50   154.198564  184.276329  169.237446
51    26.572427   56.650191   41.611309
52    34.360344   64.438109   49.399227
53    44.619063   74.696827   59.657945
54    51.631037   81.708801   66.669919
55    50.785610   80.863375   65.824492
56    32.876064   62.953828   47.914946
57    46.913949   76.991713   61.952831
58    52.198511   82.276276   67.237393
59    52.075837   82.153601   67.114719
60    81.552457  111.630222   96.591340
61    32.789397   62.867162   47.828279
62    41.673562   71.751326   56.712444
63    59.415227   89.492992   74.454110
64    54.342198   84.419962   69.381080
65    76.947916  107.025681   91.986799
66    66.945279   97.023044   81.984162
67   181.171117  211.248882  196.209999
68   194.424406  224.502170  209.463288
69    62.310913   92.388678   77.349795
70    65.666990   95.744754   80.705872
71    57.314109   87.391873   72.352991
72    60.325995   90.403759   75.364877
73    91.354259  121.432023  106.393141
74    87.882752  117.960516  102.921634
75    32.874521   62.952286   47.913404
76    47.702673   77.780437   62.741555
77    54.253254   84.331018   69.292136
78    78.409735  108.487500   93.448618
79    55.887353   85.965117   70.926235
80    80.045079  110.122843   95.083961
81    85.381511  115.459276  100.420393
82    20.094827   50.172591   35.133709
83    29.955971   60.033735   44.994853
84    45.933822   76.011586   60.972704
85   118.179137  148.256902  133.218020
86   105.405564  135.483329  120.444446
87    44.436237   74.514002   59.475119
88    42.150202   72.227966   57.189084
89    41.778589   71.856353   56.817471
90    40.367404   70.445169   55.406287
91    42.171489   72.249254   57.210372
92   132.186636  162.264401  147.225519
93   133.966921  164.044685  149.005803
94   139.357249  169.435014  154.396132
95   152.457641  182.535406  167.496524
96   161.323300  191.401065  176.362182
97   162.699148  192.776913  177.738030
98    48.572538   78.650302   63.611420
99    69.416832   99.494596   84.455714
100   76.056378  106.134142   91.095260
101   75.080994  105.158758   90.119876
102   99.818577  129.896341  114.857459
103  102.490312  132.568076  117.529194
104  115.882905  145.960670  130.921788
105  109.855442  139.933206  124.894324
106   37.181917   67.259682   52.220799
107   39.667969   69.745734   54.706851
108   23.310069   53.387833   38.348951
109   36.563357   66.641122   51.602239
110   35.949698   66.027462   50.988580
111   34.342330   64.420095   49.381213
112   35.146014   65.223779   50.184896
113   56.349825   86.427589   71.388707
114   89.712316  119.790080  104.751198
115   95.151906  125.229671  110.190788
116   93.285735  123.363499  108.324617
117  120.438595  150.516360  135.477477
118  131.797769  161.875533  146.836651
119   56.856969   86.934734   71.895852
120   80.567678  110.645442   95.606560
121   64.465475   94.543239   79.504357
122   80.246511  110.324275   95.285393
123   62.880023   92.957788   77.918906
124   59.830412   89.908177   74.869295
125   62.175681   92.253445   77.214563
126   89.284196  119.361961  104.323078
127   98.580260  128.658024  113.619142
128  128.143078  158.220842  143.181960
129   58.881984   88.959748   73.920866
130   56.859940   86.937704   71.898822
131  149.105155  179.182919  164.144037
132   43.663046   73.740811   58.701929
133   45.640985   75.718749   60.679867
134   51.128988   81.206753   66.167871
135   85.544079  115.621844  100.582961
136   81.663012  111.740777   96.701895
137   90.680656  120.758420  105.719538
138  117.788247  147.866012  132.827129
139  113.256284  143.334049  128.295167
140  120.903595  150.981359  135.942477
141   40.585807   70.663572   55.624690
142   54.081467   84.159232   69.120349
143   56.518519   86.596284   71.557401
144   76.364274  106.442039   91.403156
145  101.023537  131.101301  116.062419
146   56.312135   86.389900   71.351017
147   57.842770   87.920534   72.881652
148   64.799870   94.877635   79.838752
149   49.290153   79.367918   64.329036
150   49.281345   79.359110   64.320228
151   38.742479   68.820243   53.781361
152   41.055347   71.133112   56.094230
153   68.075875   98.153639   83.114757
154   69.508347   99.586111   84.547229
155   28.795161   58.872926   43.834043
156   32.835564   62.913328   47.874446
157   51.171891   81.249655   66.210773
158   80.428101  110.505866   95.466983
159   86.790412  116.868177  101.829294
160   86.317696  116.395460  101.356578
161   30.805037   60.882801   45.843919
162   47.545345   77.623110   62.584228
163   33.828055   63.905820   48.866937
164   41.255648   71.333413   56.294531
165   67.178367   97.256132   82.217250
166   70.425262  100.503026   85.464144
167  164.952721  195.030486  179.991604
168  180.739272  210.817037  195.778154
169   44.662878   74.740642   59.701760
170   67.786552   97.864316   82.825434
171   58.677758   88.755522   73.716640
172   83.741309  113.819074   98.780191
173   53.173157   83.250921   68.212039
174   37.053623   67.131388   52.092506
175   33.717679   63.795444   48.756562
176   30.410086   60.487851   45.448969
177   29.048944   59.126709   44.087826
178   43.221753   73.299518   58.260635
179   51.528829   81.606593   66.567711
180   55.596388   85.674152   70.635270
181   53.760899   83.838663   68.799781
182  128.951262  159.029027  143.990144
183  156.831882  186.909647  171.870764
184  169.871450  199.949214  184.910332
185   25.583529   55.661293   40.622411
186   26.465095   56.542859   41.503977
187   26.754647   56.832411   41.793529
188   44.408676   74.486441   59.447558
189   40.500385   70.578150   55.539268
190   34.673493   64.751258   49.712376
191   10.209114   40.286878   25.247996
192   16.057726   46.135490   31.096608
193   87.197290  117.275054  102.236172
194  114.742504  144.820269  129.781387
195  130.757336  160.835101  145.796219
196  157.735533  187.813298  172.774415
197   82.777316  112.855080   97.816198
198  119.262342  149.340106  134.301224
199   90.358938  120.436703  105.397821

In [24]:
df_features.loc[75]

Property_Type                            1
Club_House                               1
School_University_In_Township            0
Hospital_In_Township                     0
Mall_In_Township                         0
Park_Jogging_Track                       1
Swimming_Pool                            1
Gym                                      1
Property_Area_in_SqFt                670.0
Price_By_SubArea                      64.9
Amenities_Score                          4
Price_By_Amenities_Score         97.873505
Noun_Counts                              5
Verb_Counts                              0
Adjective_Counts                         3
boasts_elegant                           0
elegant_towers                           0
every_day                                0
great_community                          0
mantra_gold                              0
offering_bedroom                         0
quality_specification                    0
stories_offering                         0
towers_stories                           0
world_class                              0
Name: 75, dtype: object